services:
  builder:
    image: axonivy/build-container:read-the-docs-2
    user: "$UID"
    ports:
     - 8000:8000
    volumes:
     - ./..:/ivy-core
    entrypoint: make livehtml BASEDIR=/ivy-core/doc
