version: '3.3'
services:
  builder:
    image: axonivy/build-container:read-the-docs-1.0
    entrypoint: "make -C /doc-build livehtml BASEDIR=/ivy-core/doc"
    volumes:
     - "./..:/ivy-core"     
    ports:
     - "8000:8000"
