name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '21 21 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build
      run: |
        # version=dev
        # mvn -B -f pom.xml clean package -Ddoc.version=$version
        mkdir target
        docker run -v .:/doc -u $(id -u) axonivy/build-container:read-the-docs-2\
         make html BASEDIR=/doc 2> target/sphinx-errors.log
        rm build/html/portal-guide/index.html
        cat target/sphinx-errors.log\
         | sed -E 's|/doc/(.*\.rst):([0-9]+): ([A-Za-z]*): |::\L\3 file=\1,line=\2::|g'\
         | grep -v "image.not_readable"\
         | grep -v "/target/"\
         | grep -v "Could not obtain image"\
         | grep -v "Cannot scale image!"
    - name: Archive build artifact
      uses: actions/upload-artifact@v4
      with:
        name: axonivy-doc_en
        path: |
          build/html/**/*
